"""Ajout du champ etat à Reponse

Revision ID: e7380afa85ea
Revises: 7622c5c92e92
Create Date: 2025-04-17 23:23:47.007190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7380afa85ea'
down_revision = '7622c5c92e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etat', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_column('etat')

    # ### end Alembic commands ###
